### PR TITLE
Feature Design Tear down-Smashing-Magazine  

### PR DESCRIPTION
**Pull request by Temmarie**
# Design Tear down-Smashing-Magazine  
In this project, we created a heat map of  [Smashing Magazine](https://www.smashingmagazine.com/) 
webpage using only HTML5 and CSS3.

We used grid, flex and positions to create the layout.
Here is the [Live Demo Link](https://raw.githack.com/Temmarie/Smashing-Magazine/feature/index.html)

### CODE REVIEW

**Comment by Temmarie** [comment]
# Design Tear down-Smashing-Magazine  

In this project, we used grid, flex and position to create a heat map of  [Smashing Magazine](https://www.smashingmagazine.com/). 
Here is the  [Live Demo Link](https://raw.githack.com/Temmarie/Smashing-Magazine/feature/index.html)
We look forward to your feedback!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Fantastic work from you both! @Temmarie and @nellencr :medal_military: 
You have done a really great job putting this together and I commend you :+1:. There is one little detail that must be ironed out before this project can be approved. Please treat it as a hard requirement.

#### Using divs
Please note that each element in the navigation bar should be wrapped in a `div` and this `div` should be used to provide adequate positioning. Please see the requirement below
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Temmarie** [comment]
# Design Tear down-Smashing-Magazine  

- Added divs to the nav bar to position it's content as instructed by the TSE

Here is the  [Live Demo Link](https://raw.githack.com/Temmarie/Smashing-Magazine/feature/index.html)

**Review by mosesogwo — APPROVED** [review]
**Hi @Temmarie, @nellencr. Its a :heavy_check_mark: from me.**

You can now merge to master.

**Cheers:stars:**

### Status: Approved!

**Comment by Temmarie** [comment]
Thank you!!

**Pull request merged**
